name: Build and check

on: workflow_dispatch

defaults:
    run:
        shell: bash

env:
    ISSUE_NUMBER: 5
    GH_TOKEN: ${{ github.token }}

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: maven

            - name: Build
              run: ./mvnw -B package --file pom.xml

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: jar
                path: |
                    target/*.jar
    vulnerability-check:
        runs-on: ubuntu-20.04
        needs: build
        permissions:
            issues: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: jar

            # Nodeの脆弱性のチェックは事前にnpm ciが必要
            - name: Npm install
              run: npm ci

            - name: Check artifact
              uses: dependency-check/Dependency-Check_Action@main
              with:
                project: 'practice-maven'
                path: '*.jar'
                format: 'JSON'
                args: |
                    --disableAssembly
                    --suppression .github/suppression.xml
                    --scan package.json

            - name: Check results
              run: |
                BODY=$(gh issue view $ISSUE_NUMBER --json body | jq -c '.body')
                sed -r 's/.*___GITHUB_ACTIONS_DATA__ (.*)-->.*/\1/' <<< $BODY > issue.json
                echo "issue.json"
                cat issue.json
                echo "dependency-check-report.json"
                cat ${{github.workspace}}/reports/dependency-check-report.json
