name: Build and check

on: workflow_dispatch

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: maven

            - name: Build
              run: ./mvnw -B package --file pom.xml

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: jar
                path: |
                    target/*.jar
    vulnerability-check:
        runs-on: ubuntu-20.04
        needs: build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: jar
            - name: Check Artifact
              run: |
                echo "$ ls"
                ls