name: Build and check

on: workflow_dispatch

defaults:
    run:
        shell: bash

env:
    ISSUE_NUMBER: 5
    GH_TOKEN: ${{ github.token }}

jobs:
    build:
        runs-on: ubuntu-22.04
        permissions:
            issues: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
                cache: maven

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'

            # Nodeの脆弱性のチェックは事前にnpm ciが必要
            - name: Npm install
              run: npm ci

            - name: Build
              run: ./mvnw -B package --file pom.xml

            - name: Check artifact
              uses: dependency-check/Dependency-Check_Action@main
              env:
                JAVA_HOME: /opt/jdk
              with:
                project: 'practice-maven'
                path: 'package.json'
                format: 'JSON'
                args: |
                    --disableAssembly
                    --suppression .github/suppression.xml
                    --scan target/*.jar
                    --format HTML
                
            - name: Get issue
              run: |
                gh issue view $ISSUE_NUMBER --json body | jq -c '.body' --raw-output | grep '___GITHUB_ACTIONS_DATA__' | sed -r 's/.*___GITHUB_ACTIONS_DATA__ (.*)-->.*/\1/' > issue.json

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: json
                path: |
                    issue.json
                    ${{github.workspace}}/reports/dependency-check-report.html
                    ${{github.workspace}}/reports/dependency-check-report.json

            - name: Check results
              run: |
                # 前回との差分を取得する
                python3 .github/diff.py issue.json ${{github.workspace}}/reports/dependency-check-report.json diff.json
                # 差分がある場合は出力する
                python3 .github/print_diff.py diff.json
                # 差分でCVSSスコアが8以上ある脆弱性がある場合はコメントする
                python3 .github/alert_diff.py diff.json
                # 今回の診断結果をIssueにコメントする情報を作成する
                python3 .github/create_issue_body.py ${{github.workspace}}/reports/dependency-check-report.json > body.txt
 
            - name: Edit issue
              run: |
                gh issue edit $ISSUE_NUMBER --body-file body.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: report
                path: |
                    ${{github.workspace}}/reports/dependency-check-report.html
