name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@40.1.12
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
